### ISSUE TITLE
[BUG] Variable names are displayed in the chat instead of their content

### ISSUE THREAD

**Issue by stonenightcode** [ssypchenko/cs2-gungame#4]
In the ingame chat windows, it is always printed "kills.toadvance" and "leading.onweapon" instead of the variable contents.

**Comment by ssypchenko** [comment]
You need to copy lang folder 
https://github.com/ssypchenko/cs2-gungame/tree/main/lang
to the same folder where your plugin. 
![Screenshot 2024-01-09 at 22 16 05](https://github.com/ssypchenko/cs2-gungame/assets/30598453/c2bb11d8-019d-4645-82e2-8d7b497d24dd)

**Comment by stonenightcode** [comment]
Okay thanks for info the folder is present I just used your latest tag. But I did a german translation before and don't know exactly if there was a setting for it somewhere? Can't find it at least or is it in game?

**Comment by ssypchenko** [comment]
Localisation does not work now. All outputs are in English only. I'm working to find the reason and fix it.

**Comment by szogun1910** [comment]
I have the same error , only that in the config.json file in /csgo/addons/counterstrikesharp/configs I have "ServerLanguage" set: "en"

**Comment by ssypchenko** [comment]
@szogun1910 What "same" error do you have? Since v.1.0.6 the plugin does a correct translation if you have localisation files. You set the default server language to "pl". To be honest, I do not know how this affects the translation. I would advise you to make your own translation from English to Polish and put the pl.json file in the lang folder. This might solve your problem. Or temporarily change the server language to en and see how it affects you.
