### ISSUE TITLE
[IMPROVEMENT] Use proper arms race game mode and type

### ISSUE THREAD

**Issue by stonenightcode** [ssypchenko/cs2-gungame#5]
Is there any reason why you recommend using the casual gamemode and gametype?

There is already an arms race gamemode and type implemented and documented by valve but you only have a knife there (without your plugin).
It works nice at least (with your plugin). Is there any reason you don't use game_mode 0 with game_type 1 like documented here?

https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive/Game_Modes

**Comment by ssypchenko** [comment]
The reason to use the GunGame plugin instead of the standard Armsrace mode is that we can't change anything in Armsrace. 
In the GunGame Plugin you can:
- change the weapons order
- change the number of kills on each level
- add specific functionality in other plugins depending on events from GunGame (for example we changed player models on the last level to make them visible)
You can change a lot of different settings in the gungame.json file to modify plugin behaviour to your preferences. 
On our CS:GO server we did about 20 different set ups and organised weekly events. That makes the game always different. 
If you don't need that, you can use standard Armsrace mode. A lot of servers use that and they are happy (or just not aware of the GunGame plugin :))

**Comment by stonenightcode** [comment]
Alright thanks this makes sense to me 😃
